name: C Build Pipeline
on:
 push:
   branches:
     - main
   paths:
     - '**.c'
 workflow_dispatch:
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Install GCC
       run: sudo apt-get install build-essential -y

     - name: Compile hello.c
       run: gcc hello.c -o hello

     - name: Check files in directory
       run: ls -la

     - name: Run the program
       run: ./hello

     - name: Test the output
       run: |
         echo "Testing hello output..."
         chmod +x ./hello
         ./hello | grep "Hello"

     - name: Upload artifact:hello
       uses: actions/upload-artifact@v4
       with:
         name: hello-binary
         path: ./hello
