name: C Build Pipeline
on:
 push:
   branches: [ main ]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Install GCC
       run: sudo apt-get install build-essential -y
     - name: Compile hello.c
       run: gcc hello.c -o hello
     - name: Run the binary
       run: ./hello
